### ISSUE TITLE
Feat: Write a comprehensive `WYSIWYG` Tutorial for `Flutter` 📝 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/flutter-wysiwyg-editor-tutorial#1]
This is going to be one of our biggest standalone tutorials yet but it needs to be _comprehensive_ because we are going to use what we learn from this _immediately_ in our `App`. ref: https://github.com/dwyl/app/issues/275

Our `WYSIWYG` requirements for the `App` are actually quite basic https://github.com/dwyl/app/issues/275#issuecomment-1646862277 
but we need to be able to add our own **_custom_ buttons+actions** so please have that in mind when researching. 🔍  

# Todo

+ [x] Create a new `Flutter` App. 🆕 
+ [x] Research and share the available `WISYWIG` libraries. 🔍 
+ [x] Implement the most promising lib that will allow us to meet our objectives:
  + [x] **Basics**: **`B`**, _`I`_ and `U` (underline) 📝 
  + [x] Upload an in-line an image; ref: https://github.com/dwyl/flutter-image-upload-demo 🖼️ 
  + [ ] ***Advanced***: Create our own **_Custom_ Actions/Buttons** 

The _single_ most important requirement that won't immediately be clear from the the `WYSIWIG` title 
is actually _how_ the `data` gets ***transformed*** when you apply an action. 🪄 
See: https://github.com/dwyl/deltamin

The **`USP`** of what we are building is to have the _full_ history of every action that is taken
thus having full "**undo**" capability and  "***replay-ability***". 
Therefore we need to not _just_ have a `WISYWIG` lib, we need one that gives us [Operational Transform](https://en.wikipedia.org/wiki/Operational_transformation)
**So _that_** we can _easily_ store the "story" of what has happened to an `item`
and can _replay_ it both on the _connected_ devices and to _future_ team members
when they need an answer to the question: "**_How did we get `here`_**?"  

Which is why I'm leaning toward: https://github.com/singerdmx/flutter-quill or https://pub.dev/packages/quill_html_editor
which both implement [`Quill`](https://quilljs.com/docs/formats) which has [`Delta`](https://quilljs.com/docs/delta/).

Yes, I _know_ that [`YJS`](https://github.com/nelsonic/amemo/issues/62) is the `new` "hotness" in this space.
The demos are sick: https://yjs.dev/#demos
But there isn't anything in `Dart` we can use for our `Flutter App` right now ... 
Given that `Delta` is just a description language, it should be fairly easy to port to anything `else` in the future ... 💭 
So I don't have any "concerns" with using it for now.

**Comment by nelsonic** [comment]
@LuchoTurtle as soon as you're done with https://github.com/dwyl/flutter-date-time-tutorial/issues/1 please take a look at this. It's _probably_ more than `T1d` ... but we _really_ need to time-box the work to not go down too much of a rabbit hole. 🐇 

Remember our goal for _`this` repo is _fairly_ basic: "How add an _extensible_ `WYSIWYG` editor to a `Flutter` app".
We don't need to build a full-on `Google Docs` clone. Just the basics for now so we can _ship_ this in our `App`. 📱 :shipit: 🙏

**Comment by nelsonic** [comment]
A good preparation _or_ side-quest for working on this might be to _understand_ the `Delta` format by taking a look at: https://github.com/dwyl/deltamin/issues/10 💭

**Comment by LuchoTurtle** [comment]
I'm going to pick up on this now since https://github.com/dwyl/deltamin/issues/10 is already completed.

I've been scouring through the documentation of https://github.com/singerdmx/flutter-quill and inclusively watched all of the videos from https://www.youtube.com/playlist?list=PLbhaS_83B97vONkOAWGJrSXWX58et9zZ2 and I think this is perhaps the best editor we could/should go for *given the requirements you've stated*.

- it appears to have more support when compared with https://github.com/the-airbender/quill_html_editor.
- it's extendable, so we can add our own custom buttons and add embeds.
- ~~it doesn't appear to support videos just yet (ref: https://youtu.be/x_A7fjxGjtA?t=31), though there seems to be in development, as seen in https://github.com/singerdmx/flutter-quill/blob/master/flutter_quill_extensions/lib/embeds/widgets/video_app.dart~~ They support videos.
- it appears to support the `web` platform (you need to use a `defaultEmbedBuilderWeb` embed to make it work - the reason they've decided to make this separate is because the `web` version entails more dependencies that are not needed in mobile applications).
- we might have to change `deltamin` a bit, given the attributes that are possible (from https://www.youtube.com/watch?v=r502AfCX-Hw&list=PLbhaS_83B97vONkOAWGJrSXWX58et9zZ2&index=4&ab_channel=XCode and https://www.youtube.com/watch?v=oooJtULKKcc&list=PLbhaS_83B97vONkOAWGJrSXWX58et9zZ2&index=4&ab_channel=XCode). However, as of now, if we stick to the basics, it should be 100% compatible.
- appears to have `undo/redo` capabilities out-of-the-box (ref: https://github.com/singerdmx/flutter-quill/blob/master/CodeIntroduction.md).
- seems to be easier to test (they have their own utility package `'package:flutter_quill/flutter_quill_test.dart'`, which https://github.com/the-airbender/quill_html_editor doesn't appear to have).

In light of the above, this is why I believe `flutter-quill` is probably our best choice. Don't get me wrong, https://github.com/the-airbender/quill_html_editor is also a great choice but `flutter-quill` appears to have more dev activity and appears easier to test. 

I've tried to look for other options other than the two mentioned but they pale in comparison:
- https://github.com/JideGuru/rich_editor, although good, does not support `Delta`.
- https://github.com/superlistapp/super_editor, an editor made 100% in `Dart` and appears to have a [great reputation regarding their documentation and codebase.](https://www.reddit.com/r/FlutterDev/comments/uq340b/comment/i8om99d/?utm_source=share&utm_medium=web2x&context=3). Unfortunately, they do not implement `Delta`.


# Forked version?

https://github.com/visual-space/visual-editor, a **forked version of `flutter-quill`**. This one is quite interesting. The reasoning for the owner of the repo to fork the original repo is explicitly stated in https://github.com/visual-space/visual-editor/blob/develop/QUILL_FORK.md. 
Having perused the code, it's much better structured and better documented than its counterpart. The only thing that is keeping me from making a final decision between the `forked version` and the `original version` is activity.
While `flutter-quill` had code commits **2 weeks ago**, `visual-editor` had this **4 months ago**. 

@nelsonic , what do you think it's best? Maybe this repo would be a great opportunity to **try both** and see how they fare in terms of testing and compatibility with our requirements.

**Comment by nelsonic** [comment]
@LuchoTurtle agree with trying both if it doesn't add toooo much time.
The `visual-editor` looks like it has some good added features.
But I'm weary of using something that doesn't _appear_ to have any automated testing ...
https://github.com/visual-space/visual-editor/actions
![image](https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/assets/194400/b3028cf6-588f-43cb-becd-f0b9045ee7a3)

Still think that [`flutter-quill`](https://github.com/singerdmx/flutter-quill) has what we need for the foreseeable future.

**Comment by nelsonic** [comment]
@LuchoTurtle given that you've been suffering with getting both `Mobile` and `Web` working in: https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/pull/2#issuecomment-1688855119
Would it be useful to try and see if `visual-editor` solves any of them _already_? 

Opened the following issue on `visual-editor`: https://github.com/visual-space/visual-editor/issues/227 to add `GitHub Actions CI` to the repo. It should be a `~T25m` task and would add a _lot_ of value to the project - even if we don't decide to use it ourselves. 

The feature that is _most_ appealing to me in `visual-editor` is `Highlights`: 
https://github.com/visual-space/visual-editor#highlights
![image](https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/assets/194400/b713746f-a39c-487a-857a-40c3c150e1c8)

This will be on our "roadmap" as soon as I can open the issue. 
So it _could_ be worth considering testing `visual-editor` ... `if` they add `CI` for some quality assurance. 💭

**Comment by LuchoTurtle** [comment]
Nice. 
Having seen https://github.com/visual-space/visual-editor#custom-embeds, the examples shown seem to work on the web with images. So it's a good sign that I might now have to deal with the frustration that I'm currently having with image embeds in the `web` with the original repo.

**Comment by adrian-moisa** [comment]
Hey guys, I'm the lead dev on Visual Editor. If you have any questions feel free to ask. Current status of the project. Slight hiatus because we are working on our own startup go live preparations. The editor is far from dead. We have a lot more work planned ahead. I'd be happy to have more friends join the repo/effort. If you are interested in getting knees deep in the codebase I can provide the support. I've also made extensive effort to document the Quill codebase. md's are not complete but it's a far cry from previous. I've got a discord server where I keep in touch with other followers of the VE project. You'll find the link on our github readme. And I say we because my team has 5 members, all familiar and able to make contributions in Visual Editor.

**Comment by nelsonic** [comment]
@LuchoTurtle looks like you've hit a brick wall when it comes to testing with `flutter-quill` 😢 
Please record a quick screencast (30sec - 1min) of the problem you are facing (what you showed me on standup)
and share it on the issue you opened: https://github.com/singerdmx/flutter-quill/issues/1389
Then leave a quick paragraph in the `README.md` describing _why_ it's difficult to improve test coverage and linking to the issue. Then _assign_ the PR to me and we will merge it ASAP. 
Then get _straight_ to work on _replacing_ `flutter-quill` with `visual-editor`: https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/issues/3
Start by adding `CI` to the repo: https://github.com/visual-space/visual-editor/issues/227 
that will give you a chance to familiarise yourself with the codebase and open any follow-up issues.
It _should_ be a straightforward replacement given that one is a `fork` of the other ... 
But if it isn't, please comment _liberally_ on the issue: https://github.com/dwyl/flutter-wysiwyg-editor-tutorial/issues/3


For the avoidance of any further doubt: We _definitely_ don't want to _embed_ images in an `item` ***ever***. 
We want to ***always*** `upload` to a image hosting service (_currently_ `S3`) and then `link` that image using `markdown`:
```sh
![porter-200](https://factorymethod.uk/image.png?mode=fill&width=200&height=200&origin=https://world-celebs.com/public/media/resize/800x-/2019/8/5/porter-robinson-3.jpg)
```
![porter-200](https://factorymethod.uk/image.png?mode=fill&width=200&height=200&origin=https://world-celebs.com/public/media/resize/800x-/2019/8/5/porter-robinson-3.jpg)

Embedding images means the `data` of the image is stored inside the `PostgreSQL` database. 
That costs us **`10x`*** more cash and clogs up the DB making it slower with exactly zero advantage.
> **Note**: Yes, I know that it makes it more "offline friendly" to embed the image. But the cost does not justify that benefit. 
> Please just follow `GitHub` example and upload the image and link to the `![img](url)` in the body.
